# Site settings
title: 'lil bits'
email: notryanb@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Lil' bits of programming sprinkled with some hardware hacking.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://notryan.github.com" # the base hostname & protocol for your site
twitter_username: Options_r
github_username:  notryanb

# Posts
permalink: "/:title.html"

# Build settings
markdown: kramdown
highlighter: rouge
future: true
kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
